# The environment the bot is currently running in. This will determine whether slash commands
# are registered on a single guild or globally. It will also determine which Discord API Token
# to use when authenticating, as well as which Database URL.

# Steam WebAPI token
steam_token = ""

# List of `UserID`s with special privileges
owners = []

# Choose one of the two and rename it to `[environment]`.

[environment.development]
discord_token = ""
database_url = ""
users_table = ""
report_channel_id = 0
guild_id = 0

[environment.production]
discord_token = ""
database_url = ""
users_table = ""
report_channel_id = 0
