version: "3"

services:
  db:
    image: supabase/postgres
    ports:
      - "7480:5432"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: postgres
