DISCORD_TOKEN = ""
DATABASE_URL = "postgresql://postgres:postgres@localhost:5432/postgres"
USERS_TABLE = "users"
REPORT_CHANNEL_ID = "0"
GUILD_ID = "0" # only important for running locally
STEAM_TOKEN = ""
OWNER_ID = "0"
