# Discord API Token
DISCORD_TOKEN = ""

# Discord UserID of the bot's owner
#
# This needs to be a string because `shuttle-secrets` does not allow other types
OWNER_ID = "0"

# Discord GuildID for the dev server
#
# This needs to be a string because `shuttle-secrets` does not allow other types
DEV_GUILD_ID = "0"

# The ChannelID the bot should send logs to
LOGS_CHANNEL_ID = "0"

# The ChannelID the bot should send reports to
REPORTS_CHANNEL_ID = "0"

# PostgreSQL information
DATABASE_URL = "postgresql://postgres:postgres@localhost:7480/postgres"
USERS_TABLE = "users"
LOGS_TABLE = "logs"

